//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUser()
        {
            this.OrderProes = new HashSet<OrderPro>();
            AdmCreDate = DateTime.Now;
            AdmAvatar = "~/Images/ProImg/iPhone14-Plus.png";
        }

        [Display(Name = "Mã tài khoản")]
        public int AdmID { get; set; }

        [Required(ErrorMessage = "Chưa điền tên đăng nhập!")]
        [Display(Name = "Tên đăng nhập")]
        [MinLength(6, ErrorMessage = "Tên đăng nhập phải có ít nhất 6 kí tự")]
        public string AdmLogName { get; set; }

        [Required(ErrorMessage = "Chưa điền họ và tên!")]
        [Display(Name = "Họ và tên")]
        public string AdmName { get; set; }


        [Required(ErrorMessage = "Chưa điền mật khẩu!")]
        [Display(Name = "Mật khẩu")]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$", ErrorMessage = "Mật khẩu phải trên 8 kí tự và có ít nhất 1 chữ hoa, 1 chữ thường, 1 số, 1 kí tự đặc biệt")]
        [DataType(DataType.Password)]
        public string AdmPass { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Chưa xác nhận mật khẩu!")]
        [Display(Name = "Xác nhận mật khẩu")]
        [Compare("AdmPass", ErrorMessage = "Xác nhận mật khẩu không trùng khớp!")]
        [DataType(DataType.Password)]
        public string ConfirmPass { get; set; }

        [Required(ErrorMessage = "Chưa điền Email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Địa chỉ Email không đúng định dạng")]
        public string AdmEmail { get; set; }

        [Required(ErrorMessage = "Chưa điền số điện thoại!")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ!")]
        [Display(Name = "Số điện thoại")]
        public string AdmPhone { get; set; }

        [Required(ErrorMessage = "Chưa chọn giới tính!")]
        [Display(Name = "Giới tính")]
        public int AdmGender { get; set; }

        [Required(ErrorMessage = "Chưa nhập ngày sinh!")]
        [Display(Name = "Ngày sinh")]
        public System.DateTime AdmBirth { get; set; }

        [Required(ErrorMessage = "Chưa điền địa chỉ!")]
        [Display(Name = "Địa chỉ")]
        public string AdmAddress { get; set; }


        [Display(Name = "Chức vụ")]
        public Nullable<int> AdmRole { get; set; }

        [Display(Name = "Ảnh đại diện")]
        public string AdmAvatar { get; set; }

        [Display(Name = "Trạng thái hoạt động")]
        public Nullable<int> AdmStatus { get; set; }

        [Display(Name = "Kích hoạt")]
        public Nullable<bool> AdmActive { get; set; }

        [Display(Name = "Ngày tạo tài khoản")]
        public Nullable<System.DateTime> AdmCreDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [NotMapped]
        public string GioiTinh
        {
            get
            {
                switch (AdmGender)
                {
                    case 0: return "Nam";
                    case 1: return "Nữ";
                    default: return "Khác";
                }
            }
        }
    }
}
