//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Cart
    {
        public Cart()
        {
            Color = "black";
        }
        public int CartID { get; set; }
        public Nullable<int> CusID { get; set; }
        public Nullable<int> ProID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }

    }
}
