//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            DvStatus = 0;
        }

        public string Code { get; set; }
        public Nullable<int> ProID { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<int> DvStatus { get; set; }
        public string Note { get; set; }

        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [NotMapped]
        public string ProName
        {
            get
            {
                DBWebPhoneEntities db = new DBWebPhoneEntities();
                var pro = db.Products.FirstOrDefault(a => a.ProID == ProID);
                return pro.ProName;
            }
        }
    }
}
