//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Web.ModelBinding;

    public partial class OrderDetail
    {
        [Display(Name = "Mã chi tiết")]
        public int DetID { get; set; }

        [Display(Name = "Mã đơn hàng")]
        public Nullable<int> OrdID { get; set; }

        [Display(Name = "Mã thiết bị")]
        public string Code { get; set; }

        public virtual Device Device { get; set; }
        public virtual OrderPro OrderPro { get; set; }
    }
}
