//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAWebPhone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPro()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            OrdDate = DateTime.Now;
            OrdStatus = 0;
        }

        [Display(Name = "Mã đơn hàng")]
        public int OrdID { get; set; }

        [Display(Name = "Mã khách hàng")]
        public int CusID { get; set; }

        [Display(Name = "Ngày đặt đơn")]
        public System.DateTime OrdDate { get; set; }

        [Display(Name = "Tổng thanh thoán")]
        public decimal TotalPrice { get; set; }

        [Display(Name = "Địa chỉ giao hàng")]
        public string DeliAddress { get; set; }

        [Display(Name = "Trạng thái xử lý")]
        public int OrdStatus { get; set; }

        [Required(ErrorMessage = "Chưa chọn hình thức thanh toán!")]
        [Display(Name = "Hình thức mua")]
        public int PayMethod { get; set; }

        [Display(Name = "Người xử lý đơn")]
        public Nullable<int> Handler { get; set; }

        [Display(Name = "Ngày xử lý đơn")]
        public Nullable<System.DateTime> AcceptedDate { get; set; }

        public virtual AdminUser AdminUser { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [NotMapped]
        public string HinhThuc
        {
            get
            {
                if (PayMethod == 0) return "ShipCOD";
                else return "Tài khoản";
            }
        }
        [NotMapped]
        public string TrangThai
        {
            get
            {
                switch (OrdStatus)
                {
                    case 0: return "Chưa đặt";
                    case 1: return "Chờ xử lý";
                    case 2: return "Đã duyệt";
                    case 3: return "Hủy";
                    case 4: return "Bị Hủy";
                    default: return "-";
                }
            }
        }
    }
}
